### ISSUE TITLE
Update GitHub Actions to v4

### ISSUE THREAD

**Issue by teddytpc1** [wazuh/wazuh-puppet#1186]
## Description
We need to update the GH Actions `actions/upload-artifact` and `actions/download-artifact` to `v4`.
It was found that `v3` is being used in these workflows:
- https://github.com/wazuh/wazuh-puppet/blob/4.10.1/.github/workflows/main.yml
- https://github.com/wazuh/wazuh-puppet/blob/4.10.1/.github/workflows/Puppet_module_builder.yml

## Tasks
- [ ] Update the version to `v4`
- [ ] Test the workflows
- [ ] Provide evidence of a successful execution

**Comment by vcerenu** [comment]
I made the change of the actions and tested the workflow of creating the Puppet module:
https://github.com/wazuh/wazuh-puppet/actions/runs/12320517320/job/34389944680
