### ISSUE TITLE
Implement tests for installation verification

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-puppet#124]
Hello, folks

It's possible to test the integration and configuration of Wazuh Installation by using [Kitchen Puppet](https://github.com/neillturner/kitchen-puppet). Kitchen provides a driver-plugin architecture to run cookbooks against different platforms.

This implementation would provide a much easier way to test future changes and updates.

### Tasks:

- [x] Design and create tests.
- [x] Run tests against different platforms and verify results.
- [x] Update Readme.md

Cheers

**Comment by rshad** [comment]
Hi all,

Here you have a general status:

### Tasks:

- [ ] Design and create tests.
- [ ] Run tests against different platforms and verify results.
- [ ] Update Readme.md

 => Working on the design of testing for wazuh-puppet module. ***Completed*** `Initial Version`
 => Implement a successful implemenation to install wazuh manager and agent using kitchen.  ***Completed*** 
=> Tested two alternatives for machines virtualization, kitchen-vagrant and kitchen-docker, `decided to keep kitchen-docker`.
=> Investigating the resolution of errors related to kitchen activity on CentOS distribution. ***Pending***
=> Implementing simple tests as an initial step. *Completed* `Initially working with Bats tests, still need to investigate more about serverspec alternative`.

Kind regards,

Rshad

**Comment by rshad** [comment]
Hi all, 

Since last Friday, we were trying to complete `Kitchen` testing on `CentOS` distribution, using docker containers. But we faced many errors, such as : 

1 * User's permission errors.
2 * `systemctl` not available.
3 * `ossec-auth` not starting, due to the absence of `manager ssl certificate` in the system.

But to resolve the errors `1` and `2` it was sufficient to make some change in the file `kitchen.yml` such as :  `(centos agent case)`

```
  - name: centos-agent
    driver_config:
      image: centos:7
      platform: centos
      hostname: agent00_centos
      run_command: /usr/sbin/init
      run_command: /usr/lib/systemd/systemd
      dockerfile: test/Dockerfile
      build_options:
        rm: true
```

Following on the list of errors, the error `3` on which we passed most of the time, was fixed after many installations attempts on different CentOS images, comparing the installation on `vagrant` machine and `docker` containers, debugging `c` code related to `ossec-auth`, closed port: 1515?, etc ...

**Error Messages**

```
[root@agent00_centos ossec]# cat logs/ossec.log
2019/07/26 11:42:25 agent-auth: INFO: Started (pid: 1104).
2019/07/26 11:42:25 agent-auth: INFO: No authentication password provided.
2019/07/26 11:42:25 agent-auth: ERROR: Unable to connect to 10.1.0.3:1515
2019/07/26 11:48:24 ossec-agentd: CRITICAL: (1751): File client.keys not found or empty.
[root@agent00_centos ossec]#
```

```
[root@agent00_centos ossec]# telnet 10.1.0.3 1515
Trying 10.1.0.3...
telnet: connect to address 10.1.0.3: Connection refused
[root@agent00_centos ossec]#
```

```
[root@manager00_centos logs]# tail -300 ossec.log | grep -i error
2019/07/26 15:09:06 ossec-authd: ERROR: Unable to read certificate file (not found): /var/ossec/etc/sslmanager.cert
2019/07/26 15:09:06 ossec-authd: ERROR: SSL error. Exiting.
2019/07/26 15:09:16 ossec-authd: ERROR: Unable to read certificate file (not found): /var/ossec/etc/sslmanager.cert
2019/07/26 15:09:16 ossec-authd: ERROR: SSL error. Exiting.
```

As we can see, the error is related to that `ossec-auth` is not able to find the `ssl manager certificate file` which is not being created.

After a long investigation, we believed that the error is not related to `wazuh-puppet` configuration but to docker container with CentOS image; I mean some dependencies are missed in the container.

Finally the error was resolved by installing `openssl` using a Dockerfile before starting `kitchen converge` process.

```
FROM centos:7
RUN yum install -y openssl
```

Kr,

Rshad

**Comment by jm404** [comment]
Done in #139 

Regards!
