### ISSUE TITLE
Update Filebeat module

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-puppet#162]
Hi all,

It's required to update the template to make use of the latest features of Wazuh

## Tasks

- [x] Update Filebeat template

- [x] Deploy using variables to verify that are properly rendered

- [x] Update changelog.md

Best regards,

**Comment by rshad** [comment]
Hi all!

Changes are applied to the branch: [feature-162-update-filebeat-template](https://github.com/wazuh/wazuh-puppet/tree/feature-162-update-filebeat-template).

Kr,

Rshad

**Comment by rshad** [comment]
Hi all!

Changes are applied and tested. However we still need to run more tests with the manifest `filebeat.yml` as it failed with kitchen when trying to load elasticsearch repository. As the repository was not loaded successfully, we installed it manually and then installed filebeat using the corresponding manifest `filebeat.yml`

```
E: Unable to locate package filebeat
```

Still Pending for testing.

Kr,

Rshad

**Comment by rshad** [comment]
Hi all!

We have just tested the installation of FIlebeat Wazuh's module manually and it works as we were expecting. We will close this issue as the target points are all achieved and regarding the error produced in Kitchen, it will be investigated later.

Kr,

Rshad
