### ISSUE TITLE
Add explicit tasks order in manifests

### ISSUE THREAD

**Issue by rshad** [wazuh/wazuh-puppet#182]
Hi all!

**Problem Description**
We recently detected that when including the class `repo_elastic`  in `filebeat` class as follows
https://github.com/wazuh/wazuh-puppet/blob/469c1b5e85cdc6be8f96ba1c730a9fd77863e8b0/manifests/filebeat.pp#L16

The following tasks in `filebeat` class which are dependent on `repo_elastic` class do not wait till the execution of the corresponding tasks of `elastic_repo` finish. In this case, the tasks are failing as Elastic repository was not loaded yet and so `filebeat`  package can't be found by `apt`.

**Tasks To Do**
- [x] Discuss the possible solutions (Cons/Pros)
- [x] Choose the proper solution and implement it.
- [x] Verify the changes.

Kr,

Rshad

**Comment by rshad** [comment]
- Working branch: [fix-182-tasks-order](https://github.com/wazuh/wazuh-puppet/tree/fix-182-tasks-order)

**Comment by rshad** [comment]
Hi all!

To add an explicit order to the tasks in a class and specifically talking about `filebeat` and `elasticsearch` though they're the ones dependent on the class `elastic_repo`, we made the following changes:

- Added a an order statement for each of OS families (Debian, Redhat). In Debian case we obligate the execution flow to follow:
- - Download the repo.
- - Update the repositories list for `apt`.
- - Install `Filebeat` package.

https://github.com/wazuh/wazuh-puppet/blob/c71e2d6cb9c71caa3a410ab904a0bac22c2086fa/manifests/filebeat.pp#L18-L22

---

- Added `require` statement for each task depends on `filebeat` "In case of filebeat" or `elasticsearch`"In case of Elasticsearch" packages installation tasks.

https://github.com/wazuh/wazuh-puppet/blob/c71e2d6cb9c71caa3a410ab904a0bac22c2086fa/manifests/filebeat.pp#L36

https://github.com/wazuh/wazuh-puppet/blob/c71e2d6cb9c71caa3a410ab904a0bac22c2086fa/manifests/elasticsearch.pp#L43

---

`Note:` Kibana also depends on the class `elastic_repo` but as it also depends of `elasticsearch` class then it's guaranteed that it will be executed once `elasticsearch` class' execution is finished.

Kr,

Rshad
