### ISSUE TITLE
Parameterize templates

### ISSUE THREAD

**Issue by rshad** [wazuh/wazuh-puppet#186]
Hi all!

Some templates in `wazuh-puppet` are not parameterized yet.

**Tasks to Do**

- [x] Select the non-parameterized templates.
- [x] Parameterize the non-parameterized templates.
- [x] Verify the changes.

Kr,

Rshad

**Comment by rshad** [comment]
working branch: [186-parameterize-templates](https://github.com/wazuh/wazuh-puppet/tree/feature-186-parameterize-templates).

**Comment by rshad** [comment]
Hi all!

As we checked, the following list includes the templates that they are suitable for parameterizing.

- _default_activeresponse.erb
- _ruleset.erb
- _sca.erb
- _wodle_openscap.erb
- _wodle_cis_cat.erb
- _wodle_osquery.erb
- _wodle_syscollector.erb
- _wodle_vulnerability_detector.erb

Kr,

Rshad

**Comment by jm404** [comment]
Done in #187
