### ISSUE TITLE
Wazuh Release 3.11.2_7.5.1

### ISSUE THREAD

**Issue by rshad** [wazuh/wazuh-puppet#202]
Wazuh version: 3.11.2
Elastic version: 7.5.1

### Tasks

- [x] Adapt to new versions (3.11.2 - 7.5.1)

- [x] Check templates and update them if needed

- [x] Tests

- [x] Update changelog

- [ ] Tag: v3.11.2_7.5.1

- [ ] Generate and publish module on Puppet Forge

- [x] Update documentation references

- [ ] Draft release
