### ISSUE TITLE
Wazuh Release 3.11.3_7.5.2

### ISSUE THREAD

**Issue by rshad** [wazuh/wazuh-puppet#206]
Wazuh version: 3.11.3
Elastic version: 7.5.2

### Tasks

- [x] Adapt to new versions (3.11.3 - 7.5.2)

- [x] Check templates and update them if needed

- [x] Tests

- [x] Update changelog

- [x] Tag: v3.11.3_7.5.2

- [ ] Generate and publish module on Puppet Forge

- [x] Update documentation references

- [ ] Draft release
