### ISSUE TITLE
Unknown variable messages on Linux hosts

### ISSUE THREAD

**Issue by Fabian1976** [wazuh/wazuh-puppet#211]
When running the wazuh::agent class on a Linux node, these messages appear on the puppetserver:
```
2020-02-14T07:47:12.013+01:00 WARN  [qtp494186388-50] [puppetserver] Puppet Unknown variable: '::wazuh::params_agent::default_local_files'. (file: /etc/puppetlabs/code/environments/production/modules/wazuh/manifests/params_agent.pp, line: 69, column: 24)
2020-02-14T07:47:12.023+01:00 WARN  [qtp494186388-50] [puppetserver] Puppet /etc/puppetlabs/code/environments/production/modules/wazuh/data/common.yaml: file does not contain a valid yaml hash
2020-02-14T07:47:12.110+01:00 WARN  [qtp494186388-50] [puppetserver] Puppet Unknown variable: 'wazuh::params_agent::ossec_rootcheck_windows_disabled'. (file: /etc/puppetlabs/code/environments/production/modules/wazuh/manifests/agent.pp, line: 88, column: 46)
2020-02-14T07:47:12.111+01:00 WARN  [qtp494186388-50] [puppetserver] Puppet Unknown variable: 'wazuh::params_agent::ossec_rootcheck_windows_windows_apps'. (file: /etc/puppetlabs/code/environments/production/modules/wazuh/manifests/agent.pp, line: 89, column: 46)
2020-02-14T07:47:12.112+01:00 WARN  [qtp494186388-50] [puppetserver] Puppet Unknown variable: 'wazuh::params_agent::ossec_rootcheck_windows_windows_malware'. (file: /etc/puppetlabs/code/environments/production/modules/wazuh/manifests/agent.pp, line: 90, column: 46)
2020-02-14T07:47:12.113+01:00 WARN  [qtp494186388-50] [puppetserver] Puppet Unknown variable: 'wazuh::params_agent::sca_windows_enabled'. (file: /etc/puppetlabs/code/environments/production/modules/wazuh/manifests/agent.pp, line: 115, column: 26)
2020-02-14T07:47:12.114+01:00 WARN  [qtp494186388-50] [puppetserver] Puppet Unknown variable: 'wazuh::params_agent::sca_windows_scan_on_start'. (file: /etc/puppetlabs/code/environments/production/modules/wazuh/manifests/agent.pp, line: 116, column: 32)
2020-02-14T07:47:12.115+01:00 WARN  [qtp494186388-50] [puppetserver] Puppet Unknown variable: 'wazuh::params_agent::sca_windows_interval'. (file: /etc/puppetlabs/code/environments/production/modules/wazuh/manifests/agent.pp, line: 117, column: 27)
2020-02-14T07:47:12.115+01:00 WARN  [qtp494186388-50] [puppetserver] Puppet Unknown variable: 'wazuh::params_agent::sca_windows_skip_nfs'. (file: /etc/puppetlabs/code/environments/production/modules/wazuh/manifests/agent.pp, line: 118, column: 27)
2020-02-14T07:47:12.116+01:00 WARN  [qtp494186388-50] [puppetserver] Puppet Unknown variable: 'wazuh::params_agent::sca_windows_policies'. (file: /etc/puppetlabs/code/environments/production/modules/wazuh/manifests/agent.pp, line: 119, column: 27)
2020-02-14T07:47:12.117+01:00 WARN  [qtp494186388-50] [puppetserver] Puppet Unknown variable: 'wazuh::params_agent::wodle_osquery_bin_path'. (file: /etc/puppetlabs/code/environments/production/modules/wazuh/manifests/agent.pp, line: 141, column: 40)
2020-02-14T07:47:12.119+01:00 WARN  [qtp494186388-50] [puppetserver] Puppet Unknown variable: 'wazuh::params_agent::windows_audit_interval'. (file: /etc/puppetlabs/code/environments/production/modules/wazuh/manifests/agent.pp, line: 178, column: 49)
2020-02-14T07:47:12.120+01:00 WARN  [qtp494186388-50] [puppetserver] Puppet Unknown variable: 'wazuh::params_agent::active_response_windows_ca_store'. (file: /etc/puppetlabs/code/environments/production/modules/wazuh/manifests/agent.pp, line: 183, column: 47)
2020-02-14T07:47:12.121+01:00 WARN  [qtp494186388-50] [puppetserver] Puppet Unknown variable: 'wazuh::params_agent::download_path'. (file: /etc/puppetlabs/code/environments/production/modules/wazuh/manifests/agent.pp, line: 196, column: 40)
2020-02-14T07:47:12.226+01:00 WARN  [qtp494186388-50] [puppetserver] Puppet Unknown variable: 'agent_auth_option_agent'. (file: /etc/puppetlabs/code/environments/production/modules/wazuh/manifests/agent.pp, line: 506, column: 43)
```

It seems like the params are only declared when a certain condition is met (for example, the param `ossec_rootcheck_windows_disabled` is only declared in `params_agent.pp` when the OS = windows. Seems ok but in the agent class this parameter is being "used/referred to" on all hosts, and that produces these warning.

Maybe set these vars to undef for OS'es they are not used on? 

I'm using version 3.11.3

**Comment by jm404** [comment]
Hi @Fabian1976 ,

Thanks for reporting this, we will investigate approaches for this like declaring the variables to empty value so the warning doesn't appear anymore. 

The required tasks to fix this issue are:

### Tasks

- [ ] Explore approaches for this, consider if declaring null/empty variables is a possible solution

- [ ] Implement required changes

- [ ] Test the installation on Linux and Windows, ensure the `Warning` message doesn't appear.



Best regards,

Jose
