### ISSUE TITLE
Wazuh Release 3.11.4_7.6.1

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-puppet#223]
Wazuh version: 3.11.4
Elastic version: 7.6.1

### Tasks

- [x] Adapt to new versions (3.11.4 - 7.6.1)

- [x] Check templates and update them if needed

- [ ] Tests

- [x] Update changelog

- [ ] Tag: v3.11.3_7.5.2

- [ ] Generate and publish the module on Puppet Forge

- [ ] Update documentation references

- [ ] Draft release
