### ISSUE TITLE
Wazuh Release 3.12.0_7.6.1

### ISSUE THREAD

**Issue by rshad** [wazuh/wazuh-puppet#235]
Wazuh version: 3.12.0
Elastic version: 7.6.1

### Tasks

- [x] Adapt to new versions (3.12.0 - 7.6.1)

- [x] Update changelog

- [x] Check templates and update them if needed

- [x] Puppet Lint validation.

- [x] Tests

- [x] Tag: v3.12.0_7.6.1

- [x] Generate and publish the module on Puppet Forge

- [x] Update documentation references

- [x] Draft release

**Comment by rshad** [comment]
Working branch:

**Comment by rshad** [comment]
**PDK Validation**
```
pdk (INFO): Using Ruby 2.5.1
pdk (INFO): Using Puppet 6.14.0
pdk (INFO): Running all available validators...

[✔] Resolving default Gemfile dependencies.
┌ [✔] Running metadata validators ...
├── [✔] Checking metadata syntax (metadata.json tasks/*.json).
└── [✔] Checking module metadata style (metadata.json).
┌ [✔] Running puppet validators ...
├── [✔] Checking Puppet manifest syntax (**/*.pp).
└── [✔] Checking Puppet manifest style (**/*.pp).
┌ [✔] Running ruby validators ...
└── [✔] Checking Ruby code style (**/**.rb).
┌ [✔] Running tasks validators ...
├── [✔] Checking task names (tasks/**/*).
└── [✔] Checking task metadata style (tasks/*.json).
┌ [✔] Running yaml validators ...
└── [✔] Checking YAML syntax (**/*.yaml **/*.yml).

warning: puppet-lint: manifests/params_agent.pp:239:44: double quoted string containing no variables
warning: puppet-lint: manifests/params_agent.pp:240:44: double quoted string containing no variables
warning: puppet-lint: manifests/params_agent.pp:244:9: double quoted string containing no variables
warning: puppet-lint: manifests/agent.pp:227:13: double quoted string containing no variables
warning: puppet-lint: manifests/agent.pp:228:26: indentation of => is not properly aligned (expected in column 31, but found it in column 26)
warning: puppet-lint: manifests/agent.pp:230:26: indentation of => is not properly aligned (expected in column 31, but found it in column 26)
warning: puppet-lint: manifests/agent.pp:231:19: indentation of => is not properly aligned (expected in column 31, but found it in column 19)
warning: puppet-lint: manifests/audit.pp:8:3: case statement without a default case
warning: puppet-lint: manifests/audit.pp:1:1: class not documented
warning: puppet-lint: manifests/audit.pp:3:25: double quoted string containing no variables
warning: puppet-lint: manifests/audit.pp:4:30: double quoted string containing no variables
info: puppet-epp: ./: Target does not contain any files to validate (["**/*.epp"]).
info: task-name: ./: Target does not contain any files to validate (["tasks/**/*"]).
info: task-metadata-lint: ./: Target does not contain any files to validate (["tasks/*.json"]).
```
