### ISSUE TITLE
Wazuh Puppet release v3.12.1_7.6.2

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-puppet#244]
Wazuh version: 3.12.1
Elastic version: 7.6.2

### Tasks

- [ ] Adapt to new versions (3.12.1 - 7.6.2)

- [ ] Update changelog

- [ ] Check templates and update them if needed

- [ ] Puppet Lint validation.

- [ ] Tests

- [ ] Tag: v3.12.1_7.6.2

- [ ] Generate and publish the module on Puppet Forge

- [ ] Update documentation references

- [ ] Draft release
