### ISSUE TITLE
 Wazuh Puppet release v3.12.2_7.6.2

### ISSUE THREAD

**Issue by Zenidd** [wazuh/wazuh-puppet#246]
Wazuh version: 3.12.2
Elastic version: 7.6.2

### Tasks

- [x] Adapt to new versions (3.12.2 - 7.6.2)

- [x] Update changelog

- [x] Check templates and update them if needed

- [x] Puppet Lint validation.

- [x] Tests

- [ ] Tag: v3.12.2_7.6.2

- [ ] Generate and publish the module on Puppet Forge

- [ ] Update documentation references

- [ ] Draft release
