### ISSUE TITLE
Fix audit package name to deploy it on RHEL systems

### ISSUE THREAD

**Issue by wikitops** [wazuh/wazuh-puppet#257]
In the current version on wazuh-puppet, this condition is causing issues in the deployment of Auditd when you are working on RHEL systems : 

```
  if ( $ossec_syscheck_whodata_directories_1 == 'yes' ) or ( $ossec_syscheck_whodata_directories_2 == 'yes' ) {
    package { 'Installing Auditd...':
      name   => 'auditd',
    }
    service { 'auditd':
      ensure => running,
      enable => true,
    }
  }
```

The Auditd package is called 'audit' in RHEL systems. This can be fixed by using the wazuh::audit class instead of a code duplication to install Auditd.

**Comment by jm404** [comment]
Hi @wikitops,

The manager uses a custom block for installing `audit` which as you stated is not required. The manager code is: 
https://github.com/wazuh/wazuh-puppet/blob/c801e3aa8cffce4b6ee2000a586965d383cfc08f/manifests/manager.pp#L284

So it's required to change it and use the `wazuh::audit` 

Let me enumerate some task here to have a clear route when adressing the issue:

### Tasks

- [ ] Change the audit block at `manager.pp` to use `wazuh::audit`

- [ ] Delete non-necessary variables and extra code

- [ ] Test the change, paying special attention to RHEL systems

Thanks for the feedback, it's really appreciated!

Best regards,

Jose

**Comment by Zenidd** [comment]
Hello @wikitops,

Thanks for reporting this. As soon as our workflow allows us, we will investigate the best approach to ensure that `Auditd` package is correctly installed in RHEL. Thanks again for suggesting a potential fix.

The following tasks are required to fix this issue:

### Tasks

- [ ] Find the most suitable mechanism to install the Auditd package on all the supported platforms. 

- [ ] Implement required changes

- [ ] Test the installation on different Linux distros, ensure the `Auditd` package is correctly installed.

Greetings,
JP

**Comment by vaskosmihaylov** [comment]
Hello @jm404 ,

I just want to ask if we have some development on the issue?

 In the meantime, I would like to provide a workaround for the guys that want to use the **whodata** on the manager. 

1. Create a wrapper (new class for the manager.pp)
2. Use **spaceship** <| |> operator to overwrite the resource declaration for the package installation. On RHEL OS system the correct package name is **audit**, hence you should use the following:

`Package <| title == 'Installing Auditd...' |> {
    name   => 'audit',
}`

BR,
Vasko
