### ISSUE TITLE
Migrate tests to Github Actions

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-puppet#263]
Hi all,

Creating required Workflows in Github's actions would ease the testing process of the new Pull Requests opened. It would also make easier the task of publishing the Wazuh module in forge.puppet.com

### Tasks

- [x] Investigate about Github Actions and create a simple run to test it

- [x] Evaluate if it passes all the requirements: OS variety, multi containers, performance, enough hardware specs, etc...

- [x] Create a workflow to test new PRs

Best regards,

Jose

**Comment by jm404** [comment]
## Create test workflow

I created a simple workflow to run Puppet lint when someone pushes a commit.

![image](https://user-images.githubusercontent.com/46649922/83663063-a0521e80-a5c8-11ea-8d49-882e049d5e62.png)

We can improve this to auto-build the module and publish when a tag is created

**Comment by Zenidd** [comment]
## Update July 01, 2020

### Done

- The tests over different architectures (Ubuntu, CentOS, Amazon Linux) that were performed through Jenkins have been migrated to Github Actions in the wazuh-puppet repository. 
![image](https://user-images.githubusercontent.com/14923294/86267914-b3580e80-bbc7-11ea-837a-8905a4488ebb.png)

### In progress
- The linting test has yet to be implemented.
- Create the Docker image needed for the tests and upload it to Dockerhub. We are currently using the one on @jm404 repo.
- Remove the related Jenkins Pipeline.
- Remove the related files on `wazuh-qa` repo.
- Adjust the trigger to the most suitable one.

Greetings,
JP
