### ISSUE TITLE
Github Actions: Research

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-puppet#264]
Hi all,

This issue aims to keep track of the required investigation for implementing new Workflows in the repo

### Tasks

- [x]  Investigate official docs

- [x] Create a simple workflow (linting for example)

- [x] Test different approaches and OS's

Best regards,

Jose
