### ISSUE TITLE
Wazuh Puppet release v3.13.0_7.7.1

### ISSUE THREAD

**Issue by jmgarcia404** [wazuh/wazuh-puppet#267]
Wazuh version: 3.13.0
Elastic version: 7.7.1

### Tasks

- [ ] Adapt to new versions (3.13.0 - 7.7.1)

- [ ] Update changelog

- [ ] Check templates and update them if needed

- [ ] Puppet Lint validation.

- [ ] Tests

- [ ] Tag: v3.13.0_7.7.1

- [ ] Generate and publish the module on Puppet Forge

- [ ] Update documentation references

- [ ] Draft release
