### ISSUE TITLE
Wazuh Puppet release v3.13.1_7.8.0

### ISSUE THREAD

**Issue by Zenidd** [wazuh/wazuh-puppet#271]
Wazuh version: 3.13.1
Elastic version: 7.8.0

### Tasks

- [x] Adapt to new versions (3.13.1 - 7.8.0)

- [x] Update changelog

- [x] Check templates and update them if needed

- [x] Puppet Lint validation.

- [ ] Tests

- [ ] Tag: v3.13.1_7.8.0

- [ ] Generate and publish the module on Puppet Forge

- [ ] Update documentation references

- [ ] Draft release
