### ISSUE TITLE
Adapt modules to upcoming major Wazuh version 

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-puppet#278]
Hi team,

Due to the next Wazuh major version, several changes will be involved such:

- [x] Support Open Distro #277 
- [x] Remove Wazuh API package 191f190
- [x] Set TCP to default protocol 0734768
- [x] Set index pattern to wazuh-alerts-4.x
- [x] New API configuration 6c3018d
- [x] Agent auto-enrollment
- [ ] Implement Kitchen tests for ES and OD Wazuh UI https://github.com/wazuh/wazuh-puppet/issues/288
- [ ] Documentation
We have to adapt every Puppet module to Wazuh v4.0, this issue is for tracking purposes and it will be updated frequently.

Regards

**Comment by manuasir** [comment]
I'm attaching here a sample of the new `/api/configuration/api.yaml`

```
# USE THIS FILE AS A TEMPLATE. UNCOMMENT LINES TO APPLY CUSTOM CONFIGURATION
# host: 0.0.0.0
# port: 55000
# Set this option to "yes" in case the API is running behind a proxy server. Values: yes, no
# behind_proxy_server: no
# Advanced configuration
# https:
#  enabled: yes
#  key: "api/configuration/ssl/server.key"
#  cert: "api/configuration/ssl/server.crt"
#  use_ca: False
#  ca: "api/configuration/ssl/ca.crt"
# Logging configuration
# Values for API log level: disabled, info, warning, error, debug, debug2 (each level includes the previous level).
# logs:
#  level: "info"
#  path: "logs/api.log"
# Cross-origin resource sharing: https://github.com/aio-libs/aiohttp-cors#usage
# cors:
#  enabled: no
#  source_route: "*"
#  expose_headers: "*"
#  allow_headers: "*"
#  allow_credentials: no
# Cache (time in seconds)
# cache:
#  enabled: yes
#  time: 0.750
# Access parameters
# access:
#  max_login_attempts: 5
#  block_time: 300
#  max_request_per_minute: 300
# Force the use of authd when adding and removing agents. Values: yes, no
# use_only_authd: no
# Drop privileges (Run as ossec user)
# drop_privileges: yes
# Enable features under development
# experimental_features: no
```

**Comment by manuasir** [comment]
We're testing using the following `<enrollment>` block:

```
 <enrollment>
    <enabled>yes</enabled>
    <manager_address>192.168.1.100</manager_address>
    <port>1515</port>
    <agent_name>agent</agent_name>
    <groups>Group1</groups>
    <agent_address>192.168.0.110</agent_address>
    <ssl_cipher>HIGH:!ADH:!EXP:!MD5:!RC4:!3DES:!CAMELLIA:@STRENGTH</ssl_cipher>
    <server_ca_path>/path/to/server_ca</server_ca_path>
    <agent_certificate_path>/path/to/agent.cert</agent_certificate_path>
    <agent_key_path>/path/to/agent.key</agent_key_path>
    <authorization_pass>TopSecret</authorization_pass>
    <auto_method>no</auto_method>
    <delay_after_enrollment>20</delay_after_enrollment>
    <use_source_ip>no</use_source_ip>
  </enrollment>
```
