### ISSUE TITLE
Support Ubuntu 20.04 LTS (Focal Fossa)

### ISSUE THREAD

**Issue by Zenidd** [wazuh/wazuh-puppet#295]
Hi team,

## Description

Currently, the Wazuh Puppet module does not support deploying on Ubuntu 20.04 endpoints. The aim of this issue is to support deploying the module on this platform and allow the installation of all the components of Wazuh on it ( Manager, Agent, Filebeat, Elasticsearch, Kibana.. )

This issue is related to [this](https://groups.google.com/forum/#!topic/wazuh/1cErkNfGmq0) Wazuh mailing list thread.

## Tasks
 
- [ ] Add `focal` entry whenever the distro codename is checked and add the necessary resources for its case. 
- [ ] Update documentation if necessary
- [ ] Test deployments ( Agent and single host Manager)
- [ ] Consider updating `wazuh-puppet` tests to include Ubuntu 20.04 platform.

Greetings,

JP
