### ISSUE TITLE
Wazuh Puppet v4.0.4

### ISSUE THREAD

**Issue by neonmei** [wazuh/wazuh-puppet#337]
**Tasks overview**:

- [x] Bump components version
- [x] Validate configuration templates
- [x] Tests
- [x] Update changelog with summary of changes.
- [x] Update documentation to reflect new and deprecated settings.
- [x] Merge into release branch, and tag **v4.0.4**
- [x] Publish on Puppet Forge
- [x] Draft release

### Bump

Candidate versions to be included in this release (subject to change):

| Wazuh version | Elastic | ODFE   |
|---------------|---------|--------|
| v4.0.4        | 7.9.3   | 1.11.0 |
