### ISSUE TITLE
Support RHEL 8 

### ISSUE THREAD

**Issue by Zenidd** [wazuh/wazuh-puppet#348]
Hi team,

## Description

Currently, the Wazuh Puppet module does not support deploying on RHEL 8 endpoints. The aim of this issue is to support deploying the module on this platform and allow the installation of all the components of Wazuh on it ( Manager, Agent, Filebeat, Elasticsearch, Kibana.. )

This issue is related to [this](https://wazuh.slack.com/archives/C0A933R8E/p1612165292173500?thread_ts=1612163895.172000&cid=C0A933R8E) Wazuh community Slack thread.

## Tasks
 
- [ ] Add `rhel8` entry whenever the distro codename is checked and add the necessary resources for its case. 
- [ ] Update documentation if necessary
- [ ] Test deployments ( Agent and single host Manager)
- [ ] Consider updating `wazuh-puppet` tests to include rhel8 platform.

Greetings,

JP

**Comment by oletos7j** [comment]
I am also running into this problem.

`Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, This ossec module has not been tested on your distribution (file: /etc/puppetlabs/code/environments/wazuhagentupdate/modules/wazuh/manifests/agent.pp, line: 322, column: 11 on node <node_name>`

**Comment by DENISKI** [comment]
Any updates here?
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, This ossec module has not been tested on your distribution (file: /etc/puppetlabs/code/environments/puppet6/modules/wazuh/manifests/agent.pp, line: 322, column: 11) on node puppet-prod2-dsm1.c.orocloud-management.internal
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

```

**Comment by nmaludy** [comment]
+1 would like this as well

**Comment by mnsmithuk** [comment]
+1 This is very much needed.  Also add support for RHEL9 and Rocky8 (and Rocky9 for when it is released)

**Comment by sahaqaa** [comment]
Any updates on this?
There seems to be PR that adds RHEL 8 support https://github.com/wazuh/wazuh-puppet/pull/505

**Comment by cruelsmith** [comment]
Puppet RHEL 8 support for the agent has been added via #509.
But for the manager it is still hardcoded to not support it and still needs a PR or it.
