### ISSUE TITLE
_wodle_openscap.erb: undefined method `each' for nil:NilClass

### ISSUE THREAD

**Issue by maltfield** [wazuh/wazuh-puppet#46]
Hello,

OOTB my simple wazuh agent declaration fails with the following error

```
root@pclient2:~# puppet agent -t
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, Failed to parse template wazuh/wazuh_agent.conf.erb:
  Filepath: /usr/lib/ruby/vendor_ruby/puppet/parser/functions/template.rb
  Line: 26
  Detail: Failed to parse template wazuh/fragments/_wodle_openscap.erb:
  Filepath: /etc/puppet/code/environments/dev/modules/wazuh/templates/fragments/_wodle_openscap.erb
  Line: 7
  Detail: undefined method `each' for nil:NilClass

 at /etc/puppet/code/environments/dev/modules/wazuh/manifests/client.pp:110:18 on node pclient2
```

I was using the wazuh::client class as follows:

```
   class { 'wazuh::client':
      ossec_server_ip => '10.0.0.2',
   }
```

I found that I was able to fix this by explicitly setting `enable_wodle_openscap => false` as follows:

```
   class { 'wazuh::client':
      ossec_server_ip => '10.0.0.2',
      enable_wodle_openscap => false,
   }
```

However, the following documentation suggest that the `enable_wodle_openscap` flag should *already* be disabled by default:

 * https://documentation.wazuh.com/current/deploying-with-puppet/wazuh-puppet-module/reference-wazuh-puppet/wazuh-agent-class.html

So there's 2x issues here:

1. The `enable_wodle_openscap` flag is not actually set to false by default as the documentation suggests and
2. The `wodle_openscap_content` default value is Nil. I imagine this should be set to an empty array instead to fix the ruby "iteration on Nil fails" issue?

Here's some info about my system:

```
root@pclient2:~# uname -a
Linux pclient2 4.9.0-4-amd64 #1 SMP Debian 4.9.51-1 (2017-09-28) x86_64 GNU/Linux
root@pclient2:~# cat /etc/issue
Debian GNU/Linux 9 \n \l

root@pclient2:~# ruby --version
ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]
root@pclient2:~# puppet --version
4.8.2
root@pclient2:~# hiera --version
3.2.0
```

And from the puppet master:

```
# head modules/wazuh/metadata.json
{
  "name": "wazuh-wazuh",
  "version": "2.0.22",
  "author": "WAZUH",
  "summary": "Install and configure Wazuh-HIDS client and server",
  "license": "Apache-2.0",
  "source": "https://github.com/wazuh/wazuh-puppet",
  "project_page": "https://github.com/wazuh/wazuh-puppet",
  "issues_url": "https://github.com/wazuh/wazuh-puppet/issues",
  "dependencies": [
```

**Comment by jnarvaezp** [comment]
Hi @maltfield 

Thanks for the report, we're revising and fixing this bug.

Regards.

**Comment by gittygoo** [comment]
Getting the same with version 3.10.2

**Comment by jm404** [comment]
Hi @gittygoo,

The template that renders such wodle is the following:

https://github.com/wazuh/wazuh-puppet/blob/2ec765a84d6de6f40867d9951615b01c412c6533/templates/fragments/_wodle_openscap.erb#L1-L16

It requires the variable `wodle_openscap_content` to be declared in order to properly render the tamplate. By default it should be initialized but I just checked that it isn't so I will reopen the issue.

### Tasks:

- [ ] Set default `wodle_openscap_content` for each OS's

- [ ] Test that templates are properly rendered in different OS's

- [ ] Update Wazuh Documentation related to this.

- [ ] Update CHANGELOG.md


You can explicit initialize this balue in your manifests by configuring your manager manifest like the following:

```
node "agent-1" {
  class { 'wazuh::manager':
        wodle_openscap_content => {
                'ssg-ubuntu-1604-ds.xml' => {
                  'type'  => 'xccdf',
                  profiles => ['xccdf_org.ssgproject.content_profile_common'],
                },
        }
  } ->
  class { 'wazuh::wazuh_api':
           } ->
  class { 'wazuh::filebeat':
        } ->
  class { 'wazuh::elasticsearch':
        } ->
  class { 'wazuh::kibana':
        }
}
```

This will perform the full installation in the single node with the properly defined `wodle_openscap_content` variable.

Best regards,

Jose

**Comment by rshad** [comment]
Hi all!

The changes to add, commented on in this issue are already added to `wazuh-puppet`. On the following, I mentioned the related commit and the  PR.

- Commit https://github.com/wazuh/wazuh-puppet/commit/7b528cdeb19ed27a6179be637d67e2f72f4bfaaa
- PR https://github.com/wazuh/wazuh-puppet/pull/128/

Kr,

Rshad
