### ISSUE TITLE
Support new stage RC 1 for 4.5.2 in wazuh-puppet repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-puppet#748]
## Description

This issue attempts to support a new stage RC 1 for 4.5.2 in the wazuh-puppet repository.

## Tasks

- [ ] Ensure changelog is updated for 4.5.2
- [ ] Create tag v4.5.2-rc1 from branch 4.5.2 on wazuh-puppet repository.
- [ ] Create a pre-release: https://github.com/wazuh/wazuh-puppet/releases/tag/v4.5.2-rc1

**Comment by teddytpc1** [comment]
Reviewed.
