### ISSUE TITLE
Support new stage Beta 1 for 4.6.0 in wazuh-puppet repository

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh-puppet#780]
## Description

This issue attempts to support a new stage Beta 1 for 4.6.0 in the wazuh-puppet repository.

## Tasks

- [ ] Ensure changelog is updated for 4.6.0 (if applicable).
- [ ] Bump revision for branch 4.6.0 on wazuh-puppet repository.
- [ ] Change shared libraries to tag v4.6.0-beta1 in branch 4.6.0
- [ ] Create tag v4.6.0-beta1 from branch 4.6.0 on wazuh-puppet repository.
- [ ] Create and publish a pre-release: https://github.com/wazuh/wazuh-puppet/releases/tag/v4.6.0-beta1.
- [ ] Change shared libraries back to 4.6.0 in branch 4.6.0
