### ISSUE TITLE
Support new stage Alpha 1 for 4.5.4 in wazuh-puppet repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-puppet#805]
## Description

This issue attempts to support a new stage Alpha 1 for 4.5.4 in the wazuh-puppet repository.

## Tasks

- [x] Ensure changelog is updated for 4.5.4 (if applicable).
- [x] Bump revision for branch 4.5.4 on wazuh-puppet repository. https://github.com/wazuh/wazuh-puppet/pull/806
- [x] Create tag v4.5.4-alpha1 from branch 4.5.4 on wazuh-puppet repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-puppet/releases/tag/v4.5.4-alpha1.

**Comment by vcerenu** [comment]
LGTM
