### ISSUE TITLE
Support new stage RC 1 for 4.7.2 in wazuh-puppet repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-puppet#877]
## Description

This issue attempts to support a new stage RC 1 for 4.7.2 in the wazuh-puppet repository.

## Tasks

- [x] Ensure changelog is updated for 4.7.2 (if applicable).
- [x] Bump revision for branch 4.7.2 on wazuh-puppet repository.
- [x] Create tag v4.7.2-rc1 from branch 4.7.2 on wazuh-puppet repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-puppet/releases/tag/v4.7.2-rc1.
