### ISSUE TITLE
Wazuh packages redesign tier 2 - Migrate and adapt Wazuh Puppet module

### ISSUE THREAD

**Issue by teddytpc1** [wazuh/wazuh-puppet#926]
## Description 
The Wazuh Puppet module generation code should be migrated from the `wazuh-packages` repository to this one for 4.9.0.
The repository directory structure for this code must be defined with this code migration.

The tasks listed below are extracted from https://github.com/wazuh/internal-devel-requests/issues/718. Use that issue for additional information and requirements.

## Tasks
- [ ] Migrate the Wazuh Puppet module generation code into this repository
- [ ] Automate the Wazuh Puppet module generation through CI using GHA
- [ ] Add secrets to GH (to upload packages to S3)
- [ ] Add CI testing for the Wazuh Puppet module
- [ ] Upload the Wazuh Puppet module to S3 through CI

**Comment by rauldpm** [comment]
Estimated work duration: `~1 week`

**Comment by davidjiglesias** [comment]
We have decided not to do this as part of this objective.
